services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r00tpwd
      POSTGRES_DB: little-api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
